name: create-release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --verbose
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winkioskshell
        path: target\release\winkioskshell.exe
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/release/winkioskshell.exe
          LICENSE
        token: ${{ secrets.GITHUB_TOKEN }}
